version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
    networks:
      - elk

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx1g -Xms1g"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  filebeat:
    image: tech-stack-elk-filebeat-dockerlog/filebeat:1.0.0
    #command: filebeat -e -d filebeat.yml -d "publish"
    build:
      context: filebeat/
      dockerfile: Dockerfile
    volumes:
      # needed to access all docker logs (read only) : all log path in docker container
      - "/var/lib/docker/containers:/usr/share/dockerlogs/data"
      # needed to access additional informations about containers
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - elk
    depends_on:
      - logstash

networks:
  elk:
    driver: bridge
